### ISSUE TITLE
[Feature] add "format" attribute to Schema objects

### ISSUE THREAD

**Issue by galshachaf** [manchenkoff/openapi3-parser#27]
add support to the "format" property for Schema Object as described [here](https://swagger.io/specification/#schema-object):

format - See [Data Type Formats](https://swagger.io/specification/#data-type-format) for further details. While relying on JSON Schema's defined formats, the OAS offers a few additional predefined formats.

**Comment by manchenkoff** [comment]
Hey @galshachaf, which additional formats? I've just checked the links you sent and found nothing about more than already supported formats. Current format property placed here - [enumeration.py](https://github.com/manchenkoff/openapi3-parser/blob/master/src/openapi_parser/enumeration.py#L15-L35)

**Comment by galshachaf** [comment]
the Schema class should have a "format" property, used to describe, for example, that a certain string parameter is in a "date-time" format, but it's missing:

```
@dataclass
class Schema:
    type: DataType
    title: Optional[str] = None
    enum: Optional[list[Any]] = None
    example: Optional[Any] = None
    description: Optional[str] = None
    default: Optional[Any] = None
    nullable: Optional[bool] = None
    read_only: Optional[bool] = None
    write_only: Optional[bool] = None
    deprecated: Optional[bool] = None
    extensions: Optional[dict] = field(default_factory=dict)

    # all_of: Any  # TODO
    # one_of: Any  # TODO
    # any_of: Any  # TODO
    # not: Any  # TODO

```

**Comment by manchenkoff** [comment]
Yes, **Schema** itself doesn't contain format property since Schema is **not a type**, it cannot be used separately. Moreover, each DataType (_which inherits the Schema class_) has its own format - [specification.py](https://github.com/manchenkoff/openapi3-parser/blob/master/src/openapi_parser/specification.py#L76-L101). So, after parsing the document you will have many schemas, but the **format** will be available only for supported data types (_string, int, number, etc_), but not for others like an array, object, boolean.
